# Uncomment the next line to define a global platform for your project
platform :ios, '13.1'

target 'Cocoapods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cocoapods

  pod "RecastAI"

  target 'CocoapodsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CocoapodsUITests' do
    # Pods for testing
  end

end
